### ISSUE TITLE
JWT does not contain all fields in 1.0 spec

### ISSUE THREAD

**Issue by zplata** [cds-hooks/sandbox#20]
The JWT that is sent on every CDS Service invocation does not have the `sub` field in the JWT body, or the `jku` field in the JWT header. We need to update to include these fields so the Sandbox can remain compliant with the 1.0 spec in regards to services trusting EHRs.

**Comment by kpshek** [comment]
Let's hold off on the `sub` field -- we will either implement this in a separate issue/PR or forgo it altogether as it may get pulled from the specification.
