### ISSUE TITLE
change to prefetch query format in default FHIR server?

### ISSUE THREAD

**Issue by aniskand** [cds-hooks/sandbox#38]
Hello,

Our prototype cds-hooks service stopped working recently and I think I've tracked the problem down to the prefetch query. My queries are,

Condition?patient={{Patient.id}}&_sort=clinicalstatus&_sort:desc=onset

Patient/{{Patient.id}}

I'm thinking maybe the server no longer supports DSTU2 and I need to change these to the DSTU3 format, but I want make sure before I begin chasing that. Thanks.

**Comment by zplata** [comment]
Hi @aniskand - This new Sandbox complies with the 1.0 CDS Hooks specification, which includes some changes as of the last few months that affect prefetch templates. Valid prefetch keys are now variable by each hook, based on context values related to that specific hook (except for the `User` template, which is universal). See the link below for more details on prefetch in the spec. For your case, you would want to change `{{Patient.id}}` to `{{context.patientId}}`. 

http://cds-hooks.org/specification/1.0/#prefetch-template

**Comment by aniskand** [comment]
Thanks a lot, that's fixed now.

**Comment by noahprince22** [comment]
@zplata I had the same problem with our prototype. Are there announcements of new versions and changes to the sandbox interface that I can subscribe to? Also notifications for public keys changing, as that also breaks OptionGrid's prototype integration. I'd like to stay in the loop. 

Also unrelated, but fun coincidence that I'm on a project using a Cerner integration that you happen to work on, and we were in the same intern class together at Cerner. Hope you're doing well!

**Comment by kpshek** [comment]
@noahprince22 - We announced this on the Zulip chat stream at https://chat.fhir.org. Also, all of our commits here are public so you can always follow those to watch for changes.

**Comment by zplata** [comment]
@noahprince22 Great to hear from you, and cool to see you getting involved in the CDS Hooks space!

To add to Kevin's comments, the public key shouldn't regularly be rotating for this project (I think it did once, when the rewrite for this tool went public). Additionally, all merged changes are automatically reflected on the public Sandbox site, so you are seeing the latest version.
