### ISSUE TITLE
Sandbox does not save configuration

### ISSUE THREAD

**Issue by olbrich** [cds-hooks/sandbox#41]
Once I configure a service, if I refresh the page the sandbox forgets about the configuration.

**Comment by zplata** [comment]
@olbrich Are you seeing that the CDS service that you configured is not being re-configured on refresh? Or are there other Sandbox properties (FHIR server, patient, etc) that are not being persisted on a refresh?

**Comment by olbrich** [comment]
@zplata seems to just be the services I configured.  Everything else seems to persist.  FYI, I launched it from the HSPC sandbox.
