### ISSUE TITLE
feature request... A resubmit button

### ISSUE THREAD

**Issue by olbrich** [cds-hooks/sandbox#42]
When testing against a local service, it would be helpful to be able to trigger re-requesting of cds-hooks from the registered services so I can iterate quickly on testing.  Currently the only way to this is change the hook view to 'rx view' and back.

**Comment by kpshek** [comment]
This is related to #44. If we changed the behavior such that every time you click the hook tab it fires off the requests to the CDS Services, it would satisfy this issue too.

**Comment by olbrich** [comment]
It would, but it also lacks discoverability.
