### ISSUE TITLE
Adding CDS Service working properly? 

### ISSUE THREAD

**Issue by eserzowcc** [cds-hooks/sandbox#5]
I go through the steps of adding a CDS Service - After which the UI says "Configured CDS Service(s) found at the endpoint".  

I do not see the service under "Select a Service" drop down after that.  I do see it when I go to Configure CDS services, however, even if I try to delete the others I can find no way to display the service I just added in the select a service drop down.

**Comment by kpshek** [comment]
Hi @eserzowcc. Since you also posted [this to our mailing list](https://groups.google.com/d/msg/cds-hooks/xC-yPYNkGBs/muAM6k93BgAJ), I'm going to close this issue in favor of that discussion over there.

In that discussion if we do uncover an issue in the Sandbox we'll open up a new issue. 😄
