### ISSUE TITLE
Prefetch results may be dropped due to race condition

### ISSUE THREAD

**Issue by cmoesel** [cds-hooks/sandbox#54]
When there are multiple prefetches (pfA, pfB, pfC), sometimes the service is invoked with only a subset of their results even if they are all valid. This is because the logic resolves the entire sequence as soon as the last prefetch (pfC) is retrieved, even if other prefetches (pfA, pfB) are still in flight.  This bug can be demonstrated easily on the public sandbox with any service that has multiple prefetches (especially if there are many and/or the last prefetch is simpler than previous prefetches).

I've submitted pull request #53 to address this issue.

**Comment by kpshek** [comment]
Fixed in #53
