### ISSUE TITLE
How Acute/Repeat and Repeat-Reauthrization is mapped to MedicationRequest resource of CDS Hooks

### ISSUE THREAD

**Issue by jitendrasahu007** [cds-hooks/sandbox#67]
I posted the same question on Julip and got the answer as below

It's new for R4. For R3, we'll be defining a standard extension for those who want to pre-adopt. You can find the R4 preview here: http://build.fhir.org/medicationrequest.html
The solution is courseTherapyType property which is introduced in R4 version.

However, I am bit confused about the repeat-authorization. I shared the information that Renewal and repeat-re authorization both are same.
Lloyd McKenzie**  replied that 

Not in course of therapy because they're separate things. A prescription might be accute or long-term. But "accute" doesn't mean it might not require renewals. So you could have original accute and long-term prescriptions and renewal accute and long-term prescriptions. courseOfTherapy deals with accute vs. longterm. Whether something is a renewal or not is determined by whether there's a pointer back to a prior prescription.

So I think for repeat-authorization, medication request prescription should be repeated ? 

Can you please share your views on this.

**Comment by isaacvetter** [comment]
Hi @jitendrasahu007 ,

A couple of points:
1. Some housekeeping - This is really a specification question, not a question about the sandbox, right? It would be best to move your question to the spec repo: https://github.com/cds-hooks/docs/issues/
2. Ultimately, FHIR defines the content of FHIR resources, not CDS Hooks. CDS Hooks just wraps FHIR resources and uses them as the clinical content. So, in a very literal way, there's no "MedicationRequest resource of CDS Hooks". Once r4 is released, we'll add documentation to the hooks describing their use of r4 FHIR resources. 
3. I _think_ your question is this sentence:
>So I think for repeat-authorization, medication request prescription should be repeated ?

Looking at [r4 MedicationRequest's valueset](http://build.fhir.org/valueset-medicationrequest-course-of-therapy.html), I don't see "repeat" or "repeat-reauthorization". I'm guessing that you're trying to figure out how to map the `medication-prescribe` hook to authorization requests. Does the proposed [`medication-refill`](https://github.com/cds-hooks/docs/pull/432) hook help?

Isaac

References:
* [Zulip conversation with Lloyd](https://chat.fhir.org/#narrow/stream/4-implementers/topic/MedicationRequestIntent.20on.20Fhir)
* [r4 MedicationRequest](http://build.fhir.org/medicationrequest.html)
