### ISSUE TITLE
HSPC Cds hook FHIR server is not open any more?

### ISSUE THREAD

**Issue by faizalMo** [cds-hooks/sandbox#68]
Hi, I am trying to run the sandbox in my local machine and its failing because the default FHIR endpoint (https://api.hspconsortium.org/cdshooksdstu2/open/) is not open anymore. Is there anyway I can get it working in my local again?

![screen shot 2018-11-29 at 4 16 50 pm](https://user-images.githubusercontent.com/13512033/49197034-34e72980-f3f2-11e8-943e-e2d83b180a15.png)

**Comment by olbrich** [comment]
I think this also makes the 'Try it!' link on the https://cds-hooks.org/#try-it website fail.

**Comment by faizalMo** [comment]
> @nschwertner FYI in case you can help get that server online. Meanwhile you can use https://r2.smarthealthit.org and patient "smart-1288992" (note the lower case, unlike the prompt you may see).

Thanks, that worked for me.

**Comment by pz12** [comment]
This has been fixed by HSPC. Thanks for your patience!

**Comment by dennispatterson** [comment]
Linking up the Zulip thread and closing this out - https://chat.fhir.org/#narrow/stream/179159-cds-hooks/topic/Sandbox.20broken
