### ISSUE TITLE
CDS response Card array does not have any field like "status"

### ISSUE THREAD

**Issue by jitendrasahu007** [cds-hooks/sandbox#69]
Hi Team,

I would like to understand suggestion card response for CDS response object.
We definitely require status kind of field as defined by HL7 specification i.e. https://www.hl7.org/FHIR/valueset-guidance-response-status.html

This gives more information to the service user.

Is there any way we can tell the service user to call other hook if any response returned by the card is not appropriate. We are looking the solution for this kind of scenario in our business.

**Comment by isaacvetter** [comment]
Hi @jitendrasahu007 ,

This issue list is intended to be a record of bug fix & enhancement requests for the code that runs https://sandbox.cds-hooks.org/. 

I'd suggest that you ask this question in [CDS Hooks stream on the FHIR chat server](https://chat.fhir.org/#narrow/stream/17-cds-hooks).

Mind if I close this issue?

Isaac

**Comment by jitendrasahu007** [comment]
yes please close it.
