### ISSUE TITLE
Running with HAPI FHIR

### ISSUE THREAD

**Issue by robbhar** [cds-hooks/sandbox#70]
Quick question:  how to I change the port for CDS Hooks so it can coexist with HAPI on 8080?

**Comment by kpshek** [comment]
@robbhar - We're using webpack-dev-server so you can change the `dev` script in [package.json](https://github.com/cds-hooks/sandbox/blob/master/package.json#L8) to include a `--port #` parameter. See https://webpack.js.org/configuration/dev-server/#devserver-port for more information.
