### ISSUE TITLE
Add support for R4 resources

### ISSUE THREAD

**Issue by dennispatterson** [cds-hooks/sandbox#75]
The current sandbox supports dstu2 and stu3, but should be uplifted to also interact with R4 FHIR servers and be able to send R4 resources as hook context.

Also TODO: update default FHIR server to be the HSPC r4 server.

**Comment by jmandel** [comment]
Current sandbox is kind of trivially multi-version support, where each hook has logic based on the FHIR server's version

Basically it mirrors logic like the following from https://cds-hooks.org/hooks/order-select/
![image](https://user-images.githubusercontent.com/313089/60193544-795a6c80-97fd-11e9-97a7-4fe38411cc87.png)

**Comment by dennispatterson** [comment]
This also may bumping the default FHIR server to HSPC's R4 endpoint.  If we do this, it may also involve ensuring the default CDS Services also support R4

**Comment by jmandel** [comment]
@brynrhodes just assigned you based on our call this morning :)
