### ISSUE TITLE
Support ui.done messages within "Radiology Orders" tab 

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/sandbox#90]
Write a handler to receive `ui.done` operations for messages from launched SMART apps. When a `ui.done` message arrives from an app launched from the "Radiology Orders" tab, the launched app should be closed and focus returned to the "Radiology Orders" tab.

**Comment by dennispatterson** [comment]
Closing based on https://github.com/cds-hooks/sandbox/pull/115
