### ISSUE TITLE
Enable secure SMART App launch (EHR launch flow) directly from sandbox

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/sandbox#95]
Currently, the sandbox doesn't support a SMART EHR Launch for apps, unless a user first creates an account with HSPC, creates a new sandbox, and launches the CDS sandbox from there. It's a lot of prerequisites that make local development more challenging.

We should do something like:

* Render `smart` app links as non-clickable when the CDS Hooks Sandbox cannot execute a standard SMART launch (to avoid developer confusion about the expected behavior of a `smart` link)

* Update CDS Hooks to allow a standalone launch against a source FHIR Server (e.g., add a "Sign into FHIR Server" button)

* Alternatively (better still) connect to the SMART Launcher (open endpoint) by default, and enable the launcher to generate launch contexts directly. This will enable a full SMART app launch flow without developers having to take an extra sign-in step to the Sandbox by default.

**Comment by nschwertner** [comment]
Would it help if HSPC implements a "guest access" feature that sandbox owners can enable? The feature could allow app launches etc without having to be authenticate the user.

**Comment by jmandel** [comment]
It would help though it doesn't solve the problem. By default I'd like a CDS Service developer to show up at sandbox.cds-hooks.org and be able to try out the full range of capabilities, including SMART App Link cards. I have a branch that shows this behavior against the SMART launcher (which is possible because the launcher doesn't require registration of apps or user sign-in).

**Comment by VijayaraghavanPS** [comment]
Hi Josh, I am trying to get the SMART app launch option working from the cds sandbox. I tried launching the cds sandbox as a SMART app from SMART health IT launcher, but still the app launch button inside the card was disabled. Could you please let me know which branch should i use for this use case and how to do that.  I came across the branch smart-launch-without-signin. Is that the right one?
